### ISSUE TITLE
CBR filetype is not a ZIP file

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#1]
Thank you for the tool, but CBR is used for RAR compressed comic files. CBZ is the filetype for ZIP compressed files.

http://fileinfo.com/extension/cbr
http://fileinfo.com/extension/cbz
http://uti.schwa.io/identifier/com.macitbetter.cbz-archive

**Comment by pkrll** [comment]
Yes, you are absolutely right. I'll fix it, thank you.

**Comment by pkrll** [comment]
Fixed in version 2.1.5.
