### ISSUE TITLE
Change traffic status lights to cancel/clear buttons

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#11]
Not sure how you feel about this, but I'd personally would prefer a way to cancel a single item if it stalls or is taking too long without clearing the whole list/quitting or even if was an accidental addition. It would also add a quick way to clear a single item without invoking the context menu.

Thoughts?

**Comment by pkrll** [comment]
A pause button may present some issues, but a cancel button I think is a good start.
