### ISSUE TITLE
What notification is expected after queue is completed?

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#12]
There is a preference option "Notify when complete". With version 2.3.3, I don't get an alert sound, notification center alert or any other noticeable action. What should I be looking for?

When I disabled this option to test if the expected behavior was reversed (I've seen this before ;), the app crashed. It ran normally on relaunch, but still no notification.

**Comment by pkrll** [comment]
It's a bug, it should both notify and make a sound when the process is done and the window is out of focus. It worked before, so I must have done something. Why it crashed when the option was deselected, though, I must look into.

**Comment by pkrll** [comment]
@mikemcduffie The notifications (and sound alert) works for me. The notifications only show when app is out of focus, which is how it should be. But I'll be adding the sound alert, whether the app is in focus or not.

![screen shot 2015-09-26 at 22 13 22](https://cloud.githubusercontent.com/assets/140205/10119692/db8cd6ce-649c-11e5-8551-cc1ee5b90dec.png)

**Comment by mikemcduffie** [comment]
Same here. I just hadn't ran it out of focus as my tests so far have completed very quickly (3-5 folders of average comic size).

**Comment by pkrll** [comment]
Sound notification added in version 2.3.4.
