### ISSUE TITLE
Request droplet action automatically start compression

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#17]
When using the app as a droplet (dropping folders on the app or its alias), I'd recommend automatically starting the compression rather waiting for the user to press the compress button.

Rational: more in keeping with droplet app concept.

At a minimum, it would nice to have the option even if it were a `defaults write` hidden/expert pref.

**Comment by pkrll** [comment]
Added as an options setting in version 2.5.
