### ISSUE TITLE
CFBundleDocumentTypes should be set to prevent user from dragging incompatible files to app icon

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#18]
User should not be able to drag anything but folders to the app icon to launch the app. Standard Finder feedback of the circle-slash should be given to the user for incompatible files.

App's plist should have CFBundleDocumentTypes set to folders to prevent this.

<pre><code>
	&lt;key&gt;CFBundleDocumentTypes&lt;/key&gt;
	&lt;array&gt;
		&lt;dict&gt;
			&lt;key&gt;CFBundleTypeName&lt;/key&gt;
			&lt;string&gt;Folders&lt;/string&gt;
			&lt;key&gt;CFBundleTypeOSTypes&lt;/key&gt;
			&lt;array&gt;
				&lt;string&gt;fold&lt;/string&gt;
			&lt;/array&gt;
			&lt;key&gt;CFBundleTypeRole&lt;/key&gt;
			&lt;string&gt;Viewer&lt;/string&gt;
		&lt;/dict&gt;
	&lt;/array&gt;
</code></pre>

*Question: Is viewer the right app role type here? Editor doesn't seem right. Apple doesn't seem to provide for a convertor app role.*

Dragging incompatible files to the window drop target rejects them as expected, but user feedback in the form of an alert sound would help make it clear that the action is not allowed. 

Perhaps flashing a temporary red notice that the dropped files are incompatible as well?

**Comment by pkrll** [comment]
That feature is already implemented, but not working properly. But it should work now in the next update.

**Comment by pkrll** [comment]
And as for incompatible files dragged onto the app, as it is today, they "disappear" from the group of objects hovering the drop zone.

**Comment by mikemcduffie** [comment]
I guess I drag and drop too quick. I did a deliberate drag and hold and then drop and can see what you mean. The icons disappear but the count does not decrease. There is a nice bounce away action from the OS.

**Comment by mikemcduffie** [comment]
One answer on the viewer/editor discussion:

http://cocoadev.com/CFBundleTypeRole

**Comment by mikemcduffie** [comment]
Fixed for me in the 9/27 build.
