### ISSUE TITLE
App launch delay on drag and drop to app/dock icon

### ISSUE THREAD

**Issue by pkrll** [pkrll/ComicZipper-2#19]
The app launches slower than usual when opened by drag and drop to the app/dock icon.

**Comment by mikemcduffie** [comment]
Lastest version (updated 9/27) fixes this issue for me. Droplet launches are as fast as normal launches.

I used the date of the Github update as the version and build number do not appear to have been updated.

**Comment by mikemcduffie** [comment]
I spoke too soon. Initially, it was very fast to launch. After a few tests, droplet drag and drop has a noticeable delay again. 

I can't find anything obvious. I've tried different folders, but the delay on launch remains. 

Quit the app and restarted. Droplet delay remains.

Subsequent folder drags to the icon with app open are instantaneous.

**Comment by pkrll** [comment]
Does to be solved in version 2.5.
