### ISSUE TITLE
Deleting an item in the table view plays an alert sound

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#2]
Deleting an item in the table view plays an alert sound which would indicate an issue or error. If a sound is needed, why not play the system trash sound?

I would argue that since the action is immediately visible, no sound is needed. Perhaps this should be a preference option.

**Comment by pkrll** [comment]
That's not actually a feature I've implemented, seems to be some kind of default behaviour, and not something I've thought about to be honest. I agree with you that the sound is not needed. I'm not sure how to remove it, but I'll check it out.

**Comment by mikemcduffie** [comment]
I'm seeing bugs when deleting items. The first time I tested I added folders, processed/compressed them, deleted some items, added more new folders, and pressed "Compress". The app crashed. Trying to replicate this to find the specify trigger(s), I found a new issue. The new folder compressed but the app is lock in a "processing state". The new archive was created and is complete in the Finder, but the spinner Compressing is still showing and the app is not accepting new dropped items. Command-Q works.

**Comment by pkrll** [comment]
Yeah, I'm aware of those bugs, did try to fix them in the past. I've actually been meaning to start from scratch and write a whole new app, just can't seem to find the time...

**Comment by pkrll** [comment]
I've fixed the alert sound bug, and I think I've finally figured out the deletion bug. The spinner should now be fixed.

**Comment by pkrll** [comment]
I'm closing this issue, if the bugs still appear, create new issues, one for every bug.

**Comment by mikemcduffie** [comment]
Cool. I'll make a new build and check it out. You've really been busy. :)

**Comment by mikemcduffie** [comment]
Have you upgraded to 10.11/Xcode 7? Still on Xcode 6.4 (6E35b) and Mac OS X 10.10.5 here.

The latest code fails parsing:

"- (void)application:(NSApplication *)sender openFiles:(nonnull NSArray<NSString *> *)files {"

**Comment by pkrll** [comment]
Yeah, I'm on Xcode 7. But it should work now (tested it on xcode 6.4) @mikemcduffie

**Comment by mikemcduffie** [comment]
How are you managing multiple Xcode versions? Apple's relentless drive to throw away to old is a bit of the pain on older projects.

**Comment by pkrll** [comment]
I have several computers, and one of them had the older Xcode. (You can download older versions here, btw: https://developer.apple.com/downloads/)

**Comment by mikemcduffie** [comment]
Thanks. I wondered if you were using virtual machines or had a method for side-vy-side installs,

Good on the dev account here; no chinese infected Xcode for me please. :)
