### ISSUE TITLE
Request QuickLook for completed archive(s)

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#20]
I'm not sure how hard this is to implement. The cover icon is a nice touch but hard (for me) to see clearly. 

I propose pressing the spacebar with a completed archive to quicklook and a context menu item.

**Comment by pkrll** [comment]
I've had those thoughts too, but haven't look into it. It depends on how much of a hassle it'll be, but I'll look into it (though not high in priority).

**Comment by mikemcduffie** [comment]
In case I wasn't clear, I meant to support QuickLook with an already available qlgenerator; not develop a new one.

That said...  if you have any ideas how to modify SimpleComic's qlgenerator to produce a flat "stacked pages" icon instead of a "curled corner" icon, I'd love to see it. ;)
https://github.com/arauchfuss/Simple-Comic

![curled corner](https://cloud.githubusercontent.com/assets/4350221/10152216/bcfcbff8-6604-11e5-8bfb-98104512881e.png)


Yet Comic Reader, a commercial app, uses this metaphor instead of the default bundled document template (curled page corner). Unfortunately the developer prefers a flare/sheen that obscures the bottom of the image. Ironically SimpleComic's approach obscures the top of the cover image (and normally the title), so YCR's approach is the lesser of two evils to me.

![screen shot 2015-09-28 at 4 25 06 pm](https://cloud.githubusercontent.com/assets/4350221/10151549/91ae936e-65fd-11e5-94f1-9299e3f5d1bc.PNG)

I queried the developer whether he was using a standard bundled document template from the OS. English is not his first language, but I understood him to say that he provides a custom icon to the OS without a template.

<pre><code>The little trick of avoiding corner-curling-icon with quicklook generator… it is …
just simply apply your custom/generated icon on the file 
when the quick look daemon gives a chance to your plugin.
</code></pre>

Despite the fact SimpleComic hasn't been updated in years, I prefer SC for viewing comics. Additionally YCR is causing issues with file kind labeling. I'm thinking of removing it altogether as the OS gives higher precedence to App Store apps, despite the fact I've set SimpleComic as the default viewer for comic book archives.

(As sidenote, I did donate to the developer back when I started using SimpleComic as it's the best Mac comic reader app I've found. It's a shame he's no longer actively developing the app.)

Part of my motivation with ComicZipper is to use it as a "simpler" project to learn from. I hope to familiarize myself enough to go through SC's code to modernize it if needed to keep it  functioning  in newer OS versions. I tried several Mac comic apps and haven't found a better one yet.

Stretch goals:  Support cbt/webp if that becomes the standard. And correct a couple of pet peeves. ;)

**Comment by mikemcduffie** [comment]
In order to capture the page curl icon, I used a second Mac that had only SimpleComic installed. It appears YCR is applying a custom icon as the stacked pages icon was used for the comic on the second Mac. That makes sense as I reread what the YCR developer said.

In addition to showing the "icon" in the app, can you apply a custom icon to the resulting cbz archive? If so, that should work in place of a qlgenerated icon. It wouldn't need to be the stacked pages metaphor. I did a manual test paging the cover image in Finder on an archive and it looks good.

**Comment by pkrll** [comment]
A simple quicklook function was added in version 2.5.3 (05E2).
