### ISSUE TITLE
Save Preferences in Application Support folder instead of app bundle

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#21]
I'm not certain when my edits to this preference disappeared but it seem to be when I starting using yesterday's build. 

Searching ~/Library/Application Support does not find any files associated with ComicZipper. Where are is the plist  stored?

**Comment by pkrll** [comment]
The plist is actually inside the app bundle, that's why the your settings disappear between builds. It'll be added to the AppSup folder in the future (in version 2.5 which will be a bigger rewrite of the whole app).

**Comment by mikemcduffie** [comment]
Good to hear. I assumed something like that , but haven't had enough coffee yet to think to check the app bundle.

**Comment by pkrll** [comment]
Added as an options setting in version 2.5
