### ISSUE TITLE
Filesize total does not include subfolders

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#22]
Not sure if this is going to be OBE (Overcome By Events, i.e. if this function will be removed) but file size total does not include the files in subfolders.

**Comment by pkrll** [comment]
The total file size will be removed in version 2.5, but the individual item's file sizes will remain but the calculation is rewritten and now includes subfolders too.

**Comment by pkrll** [comment]
Fixed in version 2.5.
