### ISSUE TITLE
Possible enhancement: Implement zip library

### ISSUE THREAD

**Issue by pkrll** [pkrll/ComicZipper-2#23]
Consider changing zip tool from command line tool to ZipArchive (adds possibility of progress?):

https://github.com/ZipArchive/ZipArchive
https://github.com/ZipArchive/ZipArchive/issues/118

**Comment by pkrll** [comment]
I have since moved on to [ZipUtilities](https://github.com/NSProgrammer/ZipUtilities), which have been added in build 0147 of version 2.5.

**Comment by pkrll** [comment]
@mikemcduffie

**Comment by pkrll** [comment]
You can check out my progress (and the newly added progress indicators) by checking out the version 2.5 branch of the project, @mikemcduffie . I think it's still a little buggy, but it works most of the time.

**Comment by mikemcduffie** [comment]
I'll do that thanks. In the middle of El Cap clean install. Time to get rid of some cruft that's built over the years. ;)

**Comment by mikemcduffie** [comment]
OK, that is incredibly cool to see! I tested with normal size and then a 126 page el-grande folder just to watch the progress. Compressed fine each time. 

It's begging for a cancel button now (vs. the color indicator). ;)

Obviously you haven't plumbed in many of the features from the the 2.3/2.4 master branch (droplet support, preferences drawer, etc.). Do you merge the compression code back into the master or are you still rewriting the whole app on this branch?

At what point do you want assistance testing/feedback?

**Comment by pkrll** [comment]
Great! :-) There's still some bugs I think that needs to be worked out with the progress bar, but I think the most urgent ones are done.

I'm rewriting the app from scratch, mostly for separating the logic more in the code, and will add all previous features and (as much) requested features before merging the branches, I think it'll be in a week or two.

And because I'm rewriting the whole app, I'd appreciate feedback as the project progresses (with each bigger github commit, really), thanks!

(And that El Cap install seems to take a long, long time? I'd only upgraded, took like 40 minutes or so.)

**Comment by pkrll** [comment]
Added in 2.5
