### ISSUE TITLE
Enhancement: apply a custom icon to the archive file using the cover image

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#25]
ComicZipper already uses the first image in the folder structure as a file icon in the app, but does not apply the icon to the resulting cbz archive as a custom icon.

Rationale: Produces a good looking icon for the file reflecting the cover art without the corner curl obscuring the cover form the default system template. Avoids on-the-fly processing from a glgenerator each time the file is viewed in the Finder.  And makes the look of the resulting archive file in the app with the way it looks in the Finder (bonus if the text label matches the filename in the Finder :).

**Comment by mikemcduffie** [comment]
If there is no easy way to do this in Obj-C, there is a command line util `seticon` in the `osxutils` package:
https://github.com/vasi/osxutils
http://sveinbjorn.org/osxutils_docs
http://sveinbjorn.org/files/manpages/osxutils_man_pages/seticon.1.man.pdf

**Comment by pkrll** [comment]
I'm closing this one for now. I did some experimenting, but it doesn't work that great. The images get squared. I think for it to look great, you need to create a Quicklook plugin, which for me at least is a little to complex for now.
