### ISSUE TITLE
Proposed Icon for 2.5

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#28]
I use the app as a droplet primarily and as such have it on the Finder toolbar as a drag & drop target. The new icon is not clear as the old icon at small sizes. 

If you want a comic style icon, I propose a halftone logo with printing error/offset similar to the attached image. The intent was a comic sound effect. I can tweak it (font/colors/etc.) if you find this direction has merit. 

![zip icon 2](https://cloud.githubusercontent.com/assets/4350221/10330712/3bb77dd0-6c84-11e5-9bbc-427f8a73d38f.png)

![screen shot 2015-10-06 at 11 43 51 pm](https://cloud.githubusercontent.com/assets/4350221/10330700/24ec141c-6c84-11e5-8572-05cfe2f68f44.png)

**Comment by pkrll** [comment]
Yeah, I'm not that great with icons, obviously :-) But this looks really great. Is it possible to do a rounded icon, instead of a squared?

**Comment by mikemcduffie** [comment]
How about this?

![zip icon rounded](https://cloud.githubusercontent.com/assets/4350221/10331724/63a5bb1a-6c8c-11e5-9235-5c07b25a4b51.png)

Here's the Text FX alone if you want to try different backgrounds:

![zip icon text fx](https://cloud.githubusercontent.com/assets/4350221/10331729/73d2799c-6c8c-11e5-8a07-cfc836c1555b.png)

**Comment by pkrll** [comment]
Yes, that's more like it! I'll check it out after work. I appreciate your help.

**Comment by mikemcduffie** [comment]
Again with some subtle depth to the background (stoke emboss):


![zip icon embossed bg](https://cloud.githubusercontent.com/assets/4350221/10344174/a2579cc6-6cd6-11e5-9e36-43711f2d7aa3.png)

**Comment by mikemcduffie** [comment]
One more try:

![comic zip icon](https://cloud.githubusercontent.com/assets/4350221/10345760/a5391672-6ce0-11e5-8317-2aedaec08b5e.png)

**Comment by pkrll** [comment]
I think I liked the first rounded one, but I don't know. What do you think? I've added all of them to the app, you can change it by going to the Images.xcassets file in xcode and changing the names of the AppIcon-X items to test them out.

**Comment by mikemcduffie** [comment]
Either way is fine. The "sound effect" only is clearer at smaller sizes. The comic label is more obvious than just the comic style when you're focused on the icon and not the filename label. I included both to get your feedback. It' your app, so if you prefer the FX only, go for it.

Here's another take at the FX text in both versions. I figured out what was bothering me. Not enough halftone and not distressed enough. Still need to figure out how to distort the individual circles in the halftone, but I like this better.

![zip icon v3](https://cloud.githubusercontent.com/assets/4350221/10348012/85ae70c6-6ceb-11e5-9e87-2f39a6d70dae.png)

![comic zip icon v3](https://cloud.githubusercontent.com/assets/4350221/10348020/8b82ca24-6ceb-11e5-95af-5b326686f398.png)

And here's the FX text only if you want to experiment,

![zip text v3](https://cloud.githubusercontent.com/assets/4350221/10348024/8e9d9dce-6ceb-11e5-9162-8998ed9015e7.png)

**Comment by mikemcduffie** [comment]
Here's a quick & dirty comparison at various sizes:

![comiczipper icon comparision](https://cloud.githubusercontent.com/assets/4350221/10348250/d5831d9e-6cec-11e5-96e4-f13cce25087d.jpg)

**Comment by mikemcduffie** [comment]
OK, I'm starting to agree with you that the sound effect text FX only version is better.

**Comment by pkrll** [comment]
That's funny, I've actually started to like the one with the comic label more. It's make more sense.

**Comment by mikemcduffie** [comment]
I;m good either way. Here are the new versions of both. 

![comic zip icon v6](https://cloud.githubusercontent.com/assets/4350221/10360361/ffa6e610-6d54-11e5-9a90-2a285d90d661.png)

![zip icon v6-](https://cloud.githubusercontent.com/assets/4350221/10360364/0351980a-6d55-11e5-9745-7d6b85882231.png)

I can send the raw components if you want to tweak yourself.

**Comment by pkrll** [comment]
I like the new version. But it needs to be 1024x1024 (for the 512@2x icon), is that possible?

![screen shot 2015-10-08 at 09 48 25](https://cloud.githubusercontent.com/assets/140205/10360539/bf525c46-6da1-11e5-845c-c3fc67d6cc11.png)

**Comment by mikemcduffie** [comment]
Here you go:

![comic zip icon v6 1024](https://cloud.githubusercontent.com/assets/4350221/10371225/21bdb386-6d97-11e5-98e8-f66b9d9a5dd9.png)


![zip icon v6 1024](https://cloud.githubusercontent.com/assets/4350221/10371218/12890136-6d97-11e5-8dc6-9a75888dac90.png)

**Comment by mikemcduffie** [comment]
Do you have an automatic icon generation tool that supports 2x, e.g. IconKit? 

I have the full set of sizes generated based on the last full sized images above, but github will not allow attached zip files. It renames the files so I'm sure that would be a pain.

Ideas?

icon_16x16.png
icon_16x16@2x.png
icon_32x32.png
icon_32x32@2x.png
icon_128x128.png
icon_128x128@2x.png
icon_256x256.png
icon_256x256@2x.png
icon_512x512.png
icon_512x512@2x.png

![icon_16x16](https://cloud.githubusercontent.com/assets/4350221/10371448/57ab6fe6-6d98-11e5-9a40-a5b053f7b726.png)
![icon_16x16 2x](https://cloud.githubusercontent.com/assets/4350221/10371452/57d62650-6d98-11e5-9b07-b07ff32d80fa.png)
![icon_32x32](https://cloud.githubusercontent.com/assets/4350221/10371455/57de45ce-6d98-11e5-8c7a-6ae1db30d187.png)
![icon_32x32 2x](https://cloud.githubusercontent.com/assets/4350221/10371451/57d40532-6d98-11e5-84ff-937f7dcf2413.png)
![icon_128x128](https://cloud.githubusercontent.com/assets/4350221/10371454/57dca2fa-6d98-11e5-8803-d0976c8c3eb4.png)
![icon_128x128 2x](https://cloud.githubusercontent.com/assets/4350221/10371450/57cefdbc-6d98-11e5-9528-a99a935de3a5.png)
![icon_256x256](https://cloud.githubusercontent.com/assets/4350221/10371449/57c0927c-6d98-11e5-8f43-0f03e7b5c5c7.png)
![icon_256x256 2x](https://cloud.githubusercontent.com/assets/4350221/10371453/57d9d37c-6d98-11e5-95fb-ccece96c606f.png)
![icon_512x512](https://cloud.githubusercontent.com/assets/4350221/10371456/57e2ac72-6d98-11e5-91c4-7e98528362d1.png)
![icon_512x512 2x](https://cloud.githubusercontent.com/assets/4350221/10371457/57e812b6-6d98-11e5-95d3-a6a43f851f36.png)

**Comment by pkrll** [comment]
Great! Well, it's no zip, but you seemed to have uploaded them all?

**Comment by mikemcduffie** [comment]
Once more into the breach:
http://www51.zippyshare.com/v/dLKRo7XY/file.html

Preview:

![icon_256x256 2x](https://cloud.githubusercontent.com/assets/4350221/10373456/664c6e74-6da2-11e5-9a6c-c8e8b8d22007.png)

**Comment by mikemcduffie** [comment]
And v6 in case you prefer it:
http://www67.zippyshare.com/v/caOOXWyD/file.html


Preview:

![icon_256x256 2x](https://cloud.githubusercontent.com/assets/4350221/10373498/b1f71004-6da2-11e5-8376-fa8cf7946626.png)

**Comment by mikemcduffie** [comment]
What do you think of a name change to ***Comic ZIP!***   ? 

Too kitschy? 

Personally, it reminds me of the over-the-top atmosphere of the Golden Age of comics. (*That's what I was trying to invoke with the "sloppy four-color printing" halftone sound effect styled logo.*)

As a sidenote, the public domain comics at http://digitalcomicmuseum.com and http://comicbookplus.com are a great use for this app. While the contributors to these sites deserve much kudos, I often have to repackage the comics to fix page order, cleanup images, etc. 

**TADA! *Comic ZIP!* to the rescue!** *(cue dramatic music)*

Another plus is it suggests zip (cbz) format but is less rigid than "Zipper" and would still work if the app later supports rar/cbr (or even cbt if that format becomes more common).

Since "it's only software" (tongue-firmly-in-cheek as **everyone** knows software development is *easy*), if you ever decided to add converter functions\*, etc. — the name is vague enough to encompass them.


* Potential conversion functions

Input   |  Output
--------| ---------
CBZ     |  Folder
CBT     | CBZ (convert webp images to jpg)

**Comment by pkrll** [comment]
Comic Zip is actually taken. I think it's a reader app. And besides, I like the zipper part. (I'll probably not implement .rar archiving, as it doesn't seem to be possible to get the progress...)

And yes, you can rename projects, but Github warns when you try to do it. I've never done it myself so I don't know what the consequences may be.

**Comment by pkrll** [comment]
Version 6 of the icon is very nice!

**Comment by mikemcduffie** [comment]
Agree on version 6. I think I'll call this complete unless you need tweaks. I take it that the CDN worked for the icon set. 

Do you want the source files (.ai, .psd, etc.)? If so, I'd like to share them privately. Obviously the icon/png resources are easy for another effort to "rip off", but I would like to keep it from being too easy.

**Comment by pkrll** [comment]
I'd like that, you can email it perhaps? to ardalan.samimi@gmail.com

And again, I really like to give you credit for it, I'll add it to the github page, but also in the app about box. But what name?

**Comment by mikemcduffie** [comment]
I'll send the source file(s). **What format can you process (ai, psd, svg, eps)?** AI format has the most non-destructive information on how I built the sound effect logo including the halftone pattern if you want to change the font, colors, etc. down the road.

As far as name, I'm public here (never thought to use a pseudonym) so Mike McDuffie is fine. Unless you can think of some reason I shouldn't. CBZ like MP3 has a stigma due to piracy, but there's nothing illegal in the format explicitly. And there are numerous legal sources for digital comics (public domain, free comics, comics you make yourself, etc.). Thoughts?

**Comment by pkrll** [comment]
AI and PSD works, thanks!

I agree about the stigma and I understand if you would feel uncomfortable with it. Personally I'm not that bothered by it (I'm open with my name here in my profile and will add it later on in the app too when I fixed the about box). As you say, the format is not illegal. And the only thing ComicZipper really does is saving some time when it comes to creating the archives.
