### ISSUE TITLE
Quitting app during compress operation leaves corrupted/incomplete archive

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#29]
There is no dialog to ask if user wants to quit while compression is on progress. Incomplete/corrupt archive is left as a result. 

Shouldn't these be stored in a temp directory or at least under a temp filename until finished?

I checked this partially to test user inadvertent quit (⌘Q) action but also since the individual cancel control/cancel all button isn't implemented yet. I'm still hoping for a cancel control in place of the yellow traffic light.

**Comment by pkrll** [comment]
Good idea. I'm thinking it's better to store them in a temporary directory and when finished move them. This will also make it easier to cleanup when app inadvertently quits. 

The cancel button (and perhaps pause button) is on the list #11.

**Comment by pkrll** [comment]
Files are now first saved to a cache directory, then moved. Marking this as closed.
