### ISSUE TITLE
Drag and drop (droplet) support

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#3]
In the release notes it looks like you were thinking of processing folders selected in the Finder on launch. Another method to streamline Finder interaction would be to support drag and drop on the app icon or alias (dock/Finder toolbar). 

For many users, this is easier than launching the app and then dragging folders to the window target.

**Comment by pkrll** [comment]
Great idea!

**Comment by mikemcduffie** [comment]
Wow. Fast response.

I have more feedback and a crash issue to test to find the trigger(s), but wanted to wait and see how the first feedback was received. 

I currently handle CBR/CBZ through a couple of Applescript droplets but like the idea of a full featured app.  I have several enhancement type requests but wanted to see how receptive you were. Have you used the Unarchiver? It's a good example of a batch processor for this type of work.

**Comment by mikemcduffie** [comment]
Another thought is as an open source app, The Unarchiver may offer some ideas on handling the table view and the delete item/alert sound issue.

**Comment by pkrll** [comment]
I have used it, but no advance usage. Just for fast unarchiving. I'll check it out.

**Comment by pkrll** [comment]
Added in version 2.2.0
