### ISSUE TITLE
Notification & Badge functions disabled if preferences are left open

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#30]
I left the prefs window open and tested drag and drop. The main windows did not come forward automatically but compression worked correctly. However the badge counts and notifications (sound when foreground, notification when in background) all failed. Closing the pref window restored these functions.

**Comment by pkrll** [comment]
I can't recreate this bug. Not exactly. It is a little buggy. Sometimes it works, and sometimes not. The sound doesn't seem to work at all right now. I'll look into it.

**Comment by mikemcduffie** [comment]
Tried again and the badge appeared to work but the foreground sound didn't. Tried once more and the badge and the background notification worked. ¯\_(ツ)_/¯

**Comment by pkrll** [comment]
Yeah, it's a little weird. I did found one bug here though that'll create a separate issue for.

**Comment by pkrll** [comment]
Never mind, it had nothing to do with the pref window. It was just a weird if-statement that caused it. The badge seems to work perfectly now, will commit changes later though.

**Comment by pkrll** [comment]
I fixed a bug with the badge label and made the sound work again. Other than that, I haven't found anything buggy, so I'm closing this one.
