### ISSUE TITLE
Proposed: Add image file validation function

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#35]
Not sure how hard this would be to add, but it occurs to me that checking images (both for misnamed extensions and corrupt image files) would be beneficial.

(*When these hair-brained ideas get overwhelming, let me know*)

**Comment by pkrll** [comment]
I think that's beyond the scope of this app. That function should probably be an app in itself. I'm closing this one for the time being, maybe sometime in the future, but for now, CZ should be a small, fast and simple app.
