### ISSUE TITLE
2.5.1 (043C): Droplet drag filter no longer suppresses non-folder items

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#37]
Dragging non-folder items to the app icon/alias no longer rejects the items. Drawing to the app window works as expected though. (Yes, I understand these are different mechanisms ;-) 

The only issue I see in CFBundleDocumentTypes in the app plist is a **duplicate** CFBundleTypeOSTypes key:

>			<key>CFBundleTypeOSTypes</key>
>			<array>
>				<string>fold</string>
>			</array>

**Comment by pkrll** [comment]
This is a tricky one. It seems that some files are represented as folders, like zip files, and so the OS won't filter them out. I need to do more research here...

**Comment by mikemcduffie** [comment]
Here's the CFBundleDocumentTypes from a Applescript droplet I did. It will not any item except folders to be dropped on the icon/alias. I just tested this again by dragging a CBZ file to the Applescript droplet – circle slash pointer displayed and rejected the item.

>	<key>CFBundleDocumentTypes</key>
>	<array>
>		<dict>
>			<key>CFBundleTypeName</key>
>			<string>Folders</string>
>			<key>CFBundleTypeOSTypes</key>
>			<array>
>				<string>fold</string>
>			</array>
>			<key>CFBundleTypeRole</key>
>			<string>Viewer</string>
>		</dict>
>	</array>

**Comment by pkrll** [comment]
This is something I can't fix. Some files are just treated like folders by the OS, doesn't matter how many different types I try to exclude, as long as fold or public.folder or public.directory is included, they are seen as valid files. For the time being, I'm calling this an apple bug.
