### ISSUE TITLE
2.5.1 (043C): ⌘A (Select All) fails if multiple discontiguous items are selected

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#38]
Select All (⌘A) works fails if one item or multiple discontiguous items are selected. Works for no items selected or multiple contiguous items are selected.

**Comment by pkrll** [comment]
Hm. Weird. Not really sure why it does that.

**Comment by mikemcduffie** [comment]
System framework bug?

Note: haven't gotten to reviewing code yet. The icon distracted me for a while. Finishing up the Lynda.com Objective-C tutorial. Not too much of a stretch from the C, Pascal, Ada, etc. I used to do. 

Of course, familiarizing myself with the system framework classes, especially GUI ones, will take a lot longer. ;)

**Comment by mikemcduffie** [comment]
Works for one item as of 2.5.2 (051C), but discontiguous selections still fail.

**Comment by pkrll** [comment]
Check the discontiguous selections with the latest build (05CC). It seems to be working?

**Comment by mikemcduffie** [comment]
It's worked perfectly in at least the two versions.
