### ISSUE TITLE
CBR/RAR support

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#4]
While not in keeping with the app name, adding support for the CBR (RAR) format could be done by adding an option for the path to the rar program (see attached BetterZip Helpers example). This would necessitate additional controls for selecting the type of archive. "Compress as CBR" and "Compress as CBZ" buttons instead on the single "Compress" button when th is option is enabled?

![screenshot_80](https://cloud.githubusercontent.com/assets/4350221/10081206/a0662eec-62a8-11e5-92ba-cffcdfd0e609.jpg)

**Comment by mikemcduffie** [comment]
If you do decide to include the CBR/RAR option, perhaps rename to Comic Archiver?

**Comment by mikemcduffie** [comment]
Now that CZ uses a zip library, rar support no longer seems like a good fit. Am I correct that you would lose the progress bar for bar compression? 

Also since you're not excluding files during pre-processing, the war compression would need another method for exclusion as well that will almost certainly have more corner cases for what user added strings could be support (wildcards, etc.).

I recommend dropping this feature unless you have a clean implementation in mind. When zip was via external process, rar support didn't seem as bad of a fit.

**Comment by pkrll** [comment]
I'm looking into it, haven't really had time yet. But if it's possible to exclude files and get progress, then it should not be that hard to find an elegant solution.

**Comment by pkrll** [comment]
I'm closing this one for the time being as it seem to be too limited.
