### ISSUE TITLE
Drop target window lacks title bar or any description indicating what app the window belongs to

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#40]
Recommend adding more information to distinguish the window as belonging to Comic Zipper and what will happen when folders are dropped here.

![drop here](https://cloud.githubusercontent.com/assets/4350221/10380052/7e7b9f6e-6dc6-11e5-8bb2-5c05194ecc0c.jpg)

**Comment by pkrll** [comment]
I've actually been experimenting with adding an arrow image, but it's been kind of low priority

**Comment by mikemcduffie** [comment]
Any graphic resources you need? I haven't looked at how it's implemented yet, but the text description really should be more specific.

**Comment by pkrll** [comment]
Well, I'd appreciate an arrow image with a dashed border, like the one above. And also, I'm thinking, maybe a blue one to use as a highlight indicator, instead of having the whole window get highlighted? (I saw a similar thing in another app recently, look good.)

The text description is easy to fix, but I think you need a balance between a minimalistic approach and a more verbose.

**Comment by mikemcduffie** [comment]
Wouldn't an Image Well work with something like this:

![drophere](https://cloud.githubusercontent.com/assets/4350221/10380839/3330ccbe-6dcb-11e5-94d7-a11629512751.png)

I did a quick and dirty test. And it displays. I need to figure out auto layout/resizing though.

**Comment by mikemcduffie** [comment]
OK, I didn't find an auto-layout for image well but t found a pretty tutorial on auto-layout images on drop views:

https://www.youtube.com/watch?v=73oeuEgoBL4

You need to add the image in your Drop View class.

**Comment by mikemcduffie** [comment]
Bitmap or vector image? 

I thought the sample text was a good balance between too much info and not enough. You could drop "comic book archive" or alternately the "CBZ" to reduce word count but it seemed short enough to me.

**Comment by pkrll** [comment]
Oh, that's all right, it's not hard at all to add the image. You just need to use an NSImageView and add it to the window along with an NSTextField and then auto layout them. Thank you!

**Comment by mikemcduffie** [comment]
I figured out the NSImageView and did quick test with a png that I quickly knocked out/cribbed. But I couldn't figure out how to get IB to handle moving it with the text (auto layout?).  I was stuck thinking it required code to move it on window resize.

**Comment by pkrll** [comment]
You must set the add constraints (auto layout) to the image with relations to the main view. This can be done in IB, but I'm currently creating all the elements and auto layouts programmatically (but may go over to have all the objects ready in different views that'll replace each other depending on user action).

**Comment by mikemcduffie** [comment]
Are you going to use a vector image (presumably PDF) or convert the drop targets to PNGs? None of my desktops/laptop have retina displays but I assume vector is preferred nowadays. 

What is the minimum OS version for CZ so far? I assume you're using some classes/methods that require OS X 10.x (where x>0). Notifications require 10.8, but I haven't looked to see if you provided a fallback.

**Comment by pkrll** [comment]
I use png, which is I think recommended. Looks great on my retina display. Vector is usually more resource heavy.

I think minimum is 10.8, but I haven't tested the new rewritten app on it.

**Comment by mikemcduffie** [comment]
Is AppCleaner the app you were referencing for the blue highlight on drag? If so I have the color now. 

Interestingly, he uses a single black-on-white PDF vector image for the drop target, so he must be handling color dynamically for both states (gray-on-white and blue-on-white).


[github will not allow me to attach the pDF file even though that is a format that they supposedly support.]

**Comment by mikemcduffie** [comment]
Here's an alternate idea that combines the file icon design but maximizes size/clarity by using a dated folder outline:


![drop images folder here](https://cloud.githubusercontent.com/assets/4350221/10390786/b43ccdee-6e2f-11e5-90a4-57672d93d78e.png)

**Comment by mikemcduffie** [comment]
Made the folder outline a little clearer:

![drop images folder here v2](https://cloud.githubusercontent.com/assets/4350221/10390951/9c828f08-6e30-11e5-9e83-a53d5e32a5cc.png)

**Comment by pkrll** [comment]
I added the DropHere pngs you sent a couple of hours ago, to the latest build. They're not retina though.

**Comment by mikemcduffie** [comment]
Those were just placeholders until you decided which one you liked. I'll make a clean version with 2x.
