### ISSUE TITLE
2.5.1 (0465): Dot-files Regex filter only works on top level

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#43]
I previously has simple exact-name-match filters for some dot-files, e.g. ".xvpics". I removed these to test the dot-file regex expression. Before CA removed all occurrences at least 3 levels deep. With the regex filter, CZ fails to exclude any matching files in subfolders.

Any way to comment the filters? Would be helpful for the dot-files filter as it is not intuitively obvious what it does to someone unfamiliar with regex. The thumbs.db regex could probably be guessed by most users. The thumbs.db$ filter did work on all levels.

**Comment by pkrll** [comment]
Hm, odd. I'll look into why it won't exclude from subfolders.

I think that setting need it's own panel, and the default filters to be checkboxes.

**Comment by mikemcduffie** [comment]
Recommend it be in advance functions. I really don't see most users worrying with the filters (as long as the defaults take care of most of the common junk files).

**Comment by mikemcduffie** [comment]
Still not functioning correctly in 2.5.3 (0614) .

**Comment by pkrll** [comment]
Have not started on this one.

**Comment by mikemcduffie** [comment]
That's fine. I wasn't sure how much feedback you wanted.

**Comment by pkrll** [comment]
Fixed in build 06AC.

**Comment by mikemcduffie** [comment]
Working here too. ;) Thanks.

**Comment by mikemcduffie** [comment]
Oops. Spoke a little too soon. Dot-files and empty folders are excluded including several levels deep and nested, but zero-length files that otherwise don't match a known metafile category are not excluded. If this a design choice that's fine, but the preference label indicates that these files are excluded when the preference is enabled.

What do you think of sub-options for the exclusion checkbox similar to the notifications preference?

> ☑ Exclude hidden and other metadata files
>&nbsp;&nbsp;&nbsp;&nbsp;☑ Exclude thumbs.db (Windows)
>&nbsp;&nbsp;&nbsp;&nbsp;☑ Exclude dot-files (e.g., .DS_Store and other Mac OS X metadata files)
>&nbsp;&nbsp;&nbsp;&nbsp;☑ Exclude empty folders

For my personal use, I would enable all but the files may have use for some users especially if they use multiple platforms.

**Comment by pkrll** [comment]
Nope, it's a bug. Which is weird. If you do a "touch FILENAME" in terminal, wouldn't that create an empty file? Worked when I tested it. I'll look into it.

**Comment by mikemcduffie** [comment]
Attachment available until Nov 10, 2015
I created my test files using  touch as well. Here's my exclude files test file (compressed using the system function):

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAdgSbIymHjcFv7kuZQWOi1-xYAr8Aaui2jkyW_vVFKuOXXfDV1w03-2n%2F%24%7Bf%7D%3Fo%3DAvc-0wmV2uEkcK16QCraio8KIYZvPlvgB6SbJAe_hjIl%26v%3D1%26x%3D3%26a%3DBdbhzorOC3cRA8wELwEA_wHIAP8hSH3r%26e%3D1447189159%26k%3D%24%7Buk%7D%26fl%3D%26r%3D97E36A0D-7C70-4267-A7CA-45832ED875BA-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D32A49BE4-E21E-41EC-BBC4-2523B88C601D%26z%3Dhttps%253A%252F%252Fp29-content.icloud.com%26s%3D4DNvn9z_6E9LEzTzGcDrw3TTWQU&uk=W3rxh0dyZG1QYNDa0prt4w&f=Exclude%20Files.zip&sz=29997021>Exclude Files.zip
30 MB

Actually my thumbs.db files are created by touch as well and are therefore zero-length. But since they are excluded but not the other zero-length files,I assume that filter is working. I need to include real this.db files.

Mike

**Comment by pkrll** [comment]
Yeah, my bad, but it should be fixed in latest build, 06B2.

**Comment by mikemcduffie** [comment]
Your American idioms are spot on. Based on you Swedish "from my iPhone" signature and sleep cycle, I deduce you're Swedish or at least living in Sweden. I was pretty sure English was a common as a second language in Sweden, but have you spent time in the U.S.? Just curious.

Mike
