### ISSUE TITLE
Is Full Screen mode needed for this app?

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#44]
Are the "Enter Full Screen" menu item and corresponding keyboard shortcut needed for CS? 
As a drag and drop  app, it seems to me to be harder to use when fullscreen. Additional screen real estate down't appear to be an issue either.

Is this just detritus from the default Main Menu xib?

**Comment by pkrll** [comment]
Yeah, it's not intentional, I just haven't used the maximize button yet.

**Comment by mikemcduffie** [comment]
Hopefully the maximize button will resize to fit the table (to the limits to the screen) not go Fullscreen.

**Comment by pkrll** [comment]
Fixed. Working on the last suggestion, not sure if it's doable.
