### ISSUE TITLE
Rejected folders via droplet activation need more user feedback

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#45]
The item rejection visual feedback via drag to window target is very sophisticated, if somewhat subtle. However there is no feedback when a folder dropped on the icon is rejected. 

I dislike error dialogs as well, but an auto-timeout bezel window overlay or flashing the window red with message to alert the folder was reject and why (no images files, empty folder) would be helpful.

Alternately you could add the folder item to the table view with a clear indication that it will not be  processed: strike-through label text, red label text, red X or dot icon on right in place of the yellow/green normal condition. Display an error message in the subfield of the item instead of size/resulting archive info. Also a error sound would help alert the user there is an issue as well.

**Comment by pkrll** [comment]
When I have some time I'll experiment a little with your last suggestion, sounds interesting, but I need to see what it does to app performance.

**Comment by pkrll** [comment]
Added shake animation as a feedback in latest build.

**Comment by mikemcduffie** [comment]
It's actually very cool. Just starting digging to find out what's different in my droplet and CZ in regards to folder filter on droplet icon.
