### ISSUE TITLE
2.5.2 (04C1): Notification preferences are confusing

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#46]
There are two completion notifications (foreground and background states), but it is not clear to the user what these mean. Part of this is because the sub label is clipped and truncates after "Notifications will only show when the application is in...".
. 
![screen shot 2015-10-09 at 10 41 04 am](https://cloud.githubusercontent.com/assets/4350221/10401205/4be04e7c-6e72-11e5-819b-061aae7b7890.png)

The wording makes it appear the third option disables sound on completion regardless of app state. If you want to stay with the current sound when foreground and notification with sound when background, I'd recommend grouping these into one preference:

Notify when compression is completed.

with two sub options:
- Play sound when ComicZipper is active.
- Display notification when ComicZipper is in the background.

Disabling the main preference disables the checkbox function for the sub preferences.

**Comment by pkrll** [comment]
Done.
