### ISSUE TITLE
Sound is played when ⌘A (Select All) is pressed 

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#47]
Regardless of state, a sound is played. I can't think of an error condition that would need an alert sound. ⌘A and the corresponding menu item (which I do not see) should be disabled when there is nothing (or nothing more) to select.

**Comment by pkrll** [comment]
*Sigh* That damned sound again... I'm not sure what you mean about the menu item though? If nothing to select, the table view should not display.

**Comment by mikemcduffie** [comment]
I just meant add a menu item to the xib. The shortcut is there but user discovery mechanism. 

As far as nothing to select, besides the no items state (drop view), I was thinking of when all items are already selected. Reselecting again is not really an issue as long as the sound doesn't play.

**Comment by pkrll** [comment]
I'm not sure, but this one seems to have solved it self with the latest build (05CC). I don't get a sound. Please check.

**Comment by mikemcduffie** [comment]
No sound here. Your notes seemed to indicate it just disappeared,
