### ISSUE TITLE
File cleaning

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#5]
Specifically cleaning detritus like thumbs.db, DS_Store, etc.

This is something I handle hardcoded in the CBR/CBZ Applescript droplets and BetterZip provides a good user editable preference for.

![screenshot_81](https://cloud.githubusercontent.com/assets/4350221/10081777/72231218-62ab-11e5-9afa-1f7876200d36.jpg)

**Comment by pkrll** [comment]
Added in version 2.3.0

**Comment by pkrll** [comment]
This feature has been temporarily removed in version 2.5.0, due to the zip library not able to exclude certain files when zipping an entire directory. (The problem can be solved by adding the files one by one, but that's a last resort solution). It may require me to rewrite the ZipUtilities library a bit, adding it as a feature.

**Comment by pkrll** [comment]
Back again in 2.5.1.

**Comment by mikemcduffie** [comment]
Works well for non-wild card names. I tried adding ".*" to remove all hidden metadata files that Mac OS or other systems might create (one non-Mac thumbnail cache is .xvpics).

If user added wildcards are too difficult, I suggest you remove all hidden dot-files as a default. Either include a pref to turn on/off or annotate it in the readme and (potentially) in the pref heading area for user additions.

Given that this is a comic archives, would it also make sense to remove any 0 byte files regardless of filename? Empty folders as well?

**Comment by pkrll** [comment]
Wildcards can't be added, as it must currently be in a regex pattern. But this should work:  ^(\.\w+)

But, perhaps it makes more sense to include only image files (.jpg/.jpeg, .png .gif), as the app should only process those files, and remove the user defined filter all together?

**Comment by mikemcduffie** [comment]
I would recommend NOT removing all non-image files as other viewers/platforms use several of these. SFV (validation), PAR/PAR2 (validation/repair), NFO/TXT files are common. Comic Rack (Windows, Linux) uses a html file for metadata, etc. Simple Comic (Mac) supports PDF files, etc.

I would remove hidden dot-files by default as the typical user has no way to know these are there and I can think of no good reason for them in a comic archive (all the examples above are not hidden). I have seen Windows comic viewers choke on Mac metadata files. While I think this a bug as they shouldn't try to process them, it would be best not to include them.

I would also remove 0-length files.

**Comment by mikemcduffie** [comment]
Rereading your last comment, I recommend the following defaults if you remove user filters:

thumbs.db
all dot-files (includes .DS_Store)
__MACOS (and all zero length files)
empty folders

Personally, I'd prefer to keep user added filters as an **advanced feature** since covering all user needs is problematic. The file exclusion filter/function needs to communicated to the user in any event to prevent confusion.

**Comment by pkrll** [comment]
Added dot files, thumbs.db and __MACOS as default filters (though you need to remove your .plist file first, it gets added to that the first time the plist file is created). Also, empty subfolders are not compressed any more, and empty folders cannot be added to the list.
