### ISSUE TITLE
Prevent termination when compression is under way

### ISSUE THREAD

**Issue by pkrll** [pkrll/ComicZipper-2#50]
If the window closes, and the compression is still working, the app should not quit.

**Comment by pkrll** [comment]
Fixed in 2.5.2 build 05CC.

**Comment by mikemcduffie** [comment]
Still closes without warning while compressing for me in 2.5.3 (05F7).

But there is no partial file left in the user's folder. Are you cleaning up the leftover temp folder items on relaunch or relying on the system to do it? 

Reopen?

**Comment by pkrll** [comment]
They should be added to ~/library/caches/comiczipper first, and on ready moved to the user's folder- but i haven't yet implemented clear cache folder yet, so check there for leftover temps. Fix the cmd+q thing too, forgot about it. Just fixed the problem where the app quit when the window closes.

**Comment by pkrll** [comment]
Fixed in 2.5.3 (0614).
