### ISSUE TITLE
Background legibility issue with drop view image and text in when not front app

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#51]
The system "dims" the app window when not in the foreground. White on gray image and text become nearly invisible when this happens. Since iCZ is a drag and drop app, it's likely more novice users will have a finder window active for folder selection along side the ComicZipper window.

![unreadable when no active](https://cloud.githubusercontent.com/assets/4350221/10412577/e63fbae4-6f3e-11e5-94c0-409f7deaeb3b.png)

Potential resolutions:

1) change image and text color when in background

2) change window background color to better contrast with white image and text when inactive and system "dims" the window.

3) change to white background window and muted image and text (see AppCleaner for an example)

**Comment by pkrll** [comment]
I think alternative three is the best way. Takes the least amount of effort from us and less resource heavy for the app. I'll redesign the app. I think I should also create the tableview in the interface builder instead of doing it programmatically.

**Comment by pkrll** [comment]
The app no longer dims the view, but maybe change the color of the image? Check out build 065E.

**Comment by mikemcduffie** [comment]
I changed the color for you and sent a pull request. Looks pretty good to me and would work even if you changed to a white background.
