### ISSUE TITLE
Recommend changing "Filters" Pref Panel to "Exclude List" or "Exclude Files"

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#52]
Rationale: I'm not sure how many average users will understand what a filter is. Even if they don't understand Regex, they can add a simple filename to exclude from archives. Thus "Exclude List" or "Exclude Files".

Suggested Label:

> Add or remove filenames (or optionally regex expressions) below to exclude them from be added to the comic book archive.

Rationale:

The app does not remove files, but rather excludes them from being added to the archive. This is important distinction as "remove" could suggest to a user that the corresponding files in the source folder are deleted. In case of error, he user can always recover the original files from the source folder even if moved to Trash after compression.

**Comment by pkrll** [comment]
Exclude files is too long.

<img width="406" alt="screen shot 2015-10-10 at 22 13 49" src="https://cloud.githubusercontent.com/assets/140205/10413039/3db6745e-6f9c-11e5-952b-943d0a7874f7.png">

**Comment by mikemcduffie** [comment]
Exclude List?

**Comment by mikemcduffie** [comment]
Add padding?

Here's a Gemini's Pref window with a similar Panel:

![screen shot 2015-10-09 at 1 06 23 pm](https://cloud.githubusercontent.com/assets/4350221/10413088/97393ef2-6f52-11e5-8e74-6a7936df767c.png)

**Comment by pkrll** [comment]
Done in version 2.5.3 (0614).
