### ISSUE TITLE
Do you get feedback via Apple if I send a crash report?

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#53]
I'm guessing it's not registered\* with them, so NO.

Was testing clicking on various cells while compressing with a goal of testing remove an item, but it went BOOM! on the second click.

I.e. the app is not registered. But I am curious how this works for independent developers,

**Comment by pkrll** [comment]
Did you get the crash reporter dialog? As far as I know, developers don't get those crash reports.
