### ISSUE TITLE
Recommendation: Add sub-options for exclude metadata files and empty folders preference

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#56]
What do you think of sub-options for the exclusion checkbox similar to the notifications preference change?

> ☑ Exclude metadata files and empty folders
>&nbsp;&nbsp;&nbsp;&nbsp;☑ Exclude thumbs.db (Windows)
>&nbsp;&nbsp;&nbsp;&nbsp;☑ Exclude dot-files (e.g., .DS_Store and other Mac OS X hidden metadata files)
>&nbsp;&nbsp;&nbsp;&nbsp;☑ Exclude empty folders
>&nbsp;&nbsp;&nbsp;&nbsp;☑ Exclude zero-length files

For my personal use, I would enable all but the files may have use for some users especially if they use multiple platforms.

**Comment by pkrll** [comment]
I'm not as sure if these files are ever needed in a cbz-file as these are not loaded or used by the readers.

**Comment by mikemcduffie** [comment]
Understand and recommend they be ON the default. But they are currently optional in the app. 

I'd recommend either removing the option to disable or proving some granularity. I say this just because there are a lot of comic readers out there for the various platforms (Mac, Windows, Linux, iOS). I don't know what readers use what files or if the user has some workflow that prefers to leave native metadata files in place when de-archiving and re-archiving.

What reader(s) do you use? I prefer Simple Comic on the Mac and Comic Zeal on the iPad, but I'm interested if there are better alternatives. I use CDisplay on Windows but that's not my primary comic reading platform. I prefer lightweight fast readers to ones that attempt to be databases.

Mike

**Comment by mikemcduffie** [comment]
I've started a branch for this. Here's a modified version of the View Filters panel: 

![screen shot 2015-10-11 at 5 07 54 pm](https://cloud.githubusercontent.com/assets/4350221/10419913/afa0ba04-703a-11e5-8d63-080a3fa6d74f.png)

**Comment by pkrll** [comment]
I've implemented it. But I'll probably make some changes in the near future. Does not make sense to have one setting for empty folders, and one setting for empty files. If they are empty, they serve no purpose. Hidden files and subfolders, on the other hand, may have different purposes.

**Comment by mikemcduffie** [comment]
I view them as different because you can put a placeholder file in for a missing page using touch, etc. Old public domain scans sometimes are sometimes incomplete. 

Admittedly it would be a non-issue if the user makes the placeholder file non-zero. That was my rationale for the bifurcation.

**Comment by pkrll** [comment]
I see. But I really don't think we should encourage that kind of behaviour :)

**Comment by mikemcduffie** [comment]
The intent is for the placeholder for archive organization outside the comic reader. I don't expect any viewer to handle these files.

**Comment by mikemcduffie** [comment]
I don't plan to use them myself, I was just thinking ways the users might use zero-length filesor in case of another use I didn't think of. 

All this said, it's not the end of the world if they're unified to one setting.
