### ISSUE TITLE
Recommendation: Default preferences 

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#57]
I'm curious why the general features are disabled by default:

* Notify when compression is done
* Dock badge icon

The Exclude List has the hidden/metadata pref disabled but includes filters in the exclude list for several of these. Recommend emptying the list and checking the base pref as a default.

Is this something you would welcome as a Pull Request?

**Comment by pkrll** [comment]
Not intentional. Just something I haven't thought of. Please do, if you can.
