### ISSUE TITLE
2.5.3 (06AC): App name no longer display on window title bar

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#59]
You had added the app name previously to the title bar, but it's no longer displayed in 2.5.3 (06AC). Recommend adding it back as it makes it clearer what app the window belongs to.

**Comment by pkrll** [comment]
Yeah. Thing is, I'm trying out a unified title and toolbar. But I haven't figured out how to get the title back like in Appcleaner. I'm working on it.

**Comment by mikemcduffie** [comment]
Apple's flat appearance leaves somethings be desired. Looks like the title bar is there but blank.

**Comment by mikemcduffie** [comment]
When you say unified title and toolbar do you mean something like AppCleaner:

![screen shot 2015-10-11 at 1 29 13 pm](https://cloud.githubusercontent.com/assets/4350221/10418894/19b195a4-701c-11e5-995b-e0627e89a6c5.png)

Or are you referring to the notification are in the table view?

**Comment by pkrll** [comment]
Yup, as in Appcleaner.

**Comment by pkrll** [comment]
The title is back. And background is now white (but grey when the table is displayed. This was what was bothering me. The white against the tables white rows made it look weird).

**Comment by mikemcduffie** [comment]
Looks really good.
