### ISSUE TITLE
Improved Metadata files/folders exclusion handling

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#61]
I'm filing this as a new bug:

1) because the old bug is closed

2) I did some research on typical metadata files and found some new corner cases that need to be added (I think)

* hidden (dot-name) directories
* __MACOS directory

I'll send an updated excluded files v1.1 test file. (Weird, I can send an email reply with zip attachment but I can't attach a zip file with the web interface).

I also changed the test file to use actual thumbs.db files and changed the dot-files to non-zero length so they get tested separately from the zero-length file filter. I also renamed the zero-length files to the obvious name for testing.

**Comment by pkrll** [comment]
Directories (hidden or not) that have legit files in it should not be removed by the app. That should be up to the user.

__MACOSX directories I think are basically the same as thumbs.db. So that setting should be "Thumbs.db and __MACOSX" or something.

**Comment by mikemcduffie** [comment]
Perhaps:

[x] Exclude system metadata files (__MACOSX and Thumbs.db)

Note: the Title case on "Thumbs.db". I goofed in my original test file (created with `touch`). The real files in `Exclude Files v1.1` caught this. I have the changes and can do a Pull Request if you prefer.

**Comment by mikemcduffie** [comment]
I was iffy on hidden folders with files that don't match the current filters. I ned to look at how Mac handles metadata on foreign file systems. That would be the most likely culprit. Scan on PC*, thumbstick over (yay sneaker net!), and cleanup etc on Mac. 

\* Scanner support on Mac is OFTEN a victim to Apple's relentless system updates and manufacturers' economic disincentive to update.
