### ISSUE TITLE
About dialog should credit Nolan O'Brien for ZipUtilities

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#64]
Although it's covered in the README and the license doesn't require it to my understanding, it seems the right thing to do. 

A hyperlink to either the ZipUtilities github project page or alternately the NSProgrammer website would be a good idea. I could make a branch if you like.

Sidenote: The MIT license for ZipUtilities requires a copy pf the license be included. Should this be handled in the app bundle, project files, a separate document when/if distributed, or somewhere else?

**Comment by pkrll** [comment]
Not the about box. But the help book, a section in the back? I've added a label in the about box that will point to a acknowledgments window/page.

**Comment by mikemcduffie** [comment]
Cool!

**Comment by mikemcduffie** [comment]
Help Book is in progress. I have a template in place and am working on organization. I'll do placeholder graphics but if you want retina images, you'll have to redo those.

**Comment by pkrll** [comment]
Sounds good.

**Comment by mikemcduffie** [comment]
Do you wire up the Help menu to the help book or is it automatic? Add another Help menu item  for direct link to github project page?

**Comment by pkrll** [comment]
You actually create a HTML file, that you hook up somehow (I forget) and the apple help viewer will take care of the rest. See https://developer.apple.com/library/mac/documentation/Carbon/Conceptual/ProvidingUserAssitAppleHelp/authoring_help/authoring_help_book.html for more information

**Comment by mikemcduffie** [comment]
Yes I have the bundle with mandated internal structure (including plist) created with place holder text. I changed the Menu Item (cosmetic) but the documentation doesn't say how to wire it up. My quick test failed.

**Comment by pkrll** [comment]
You need to bind the menu item in the interface builder to the first responder method showHelp:

**Comment by pkrll** [comment]
Here's more information: https://developer.apple.com/library/mac/documentation/Carbon/Conceptual/ProvidingUserAssitAppleHelp/registering_help/registering_help.html

**Comment by mikemcduffie** [comment]
I found the same page in my searches, but it's seriously out of date. The URL contains a Carbon reference! But I'll look at it again.

**Comment by mikemcduffie** [comment]
I assume you mean app info.plist. There is some overlap between it and the Help bindle info.plist, but that is not unexpected.

**Comment by pkrll** [comment]
Yes, the app info.plist. The documentation is for both carbon and cocoa apps.

**Comment by mikemcduffie** [comment]
`ComicZipper help` menu item first responder was already set to `showHelp:`

`Help Book directory name` key with value `ComicZipper.Help` added to app's info plist

`ComicZipper.Help` bundle added to project with `Create folder references`

Checked to make sure the build had the `ComicZipper.Help` bundle in `ComicZipper.app/Contents/Resources`

Help menu selection still produce error: `Help isn’t available for ComicZipper.`

No bueno!

**Comment by mikemcduffie** [comment]
Figured it out. I was missing the CFBundleHelpBookName key. It works, I t just have to finish editing the html. :)

I'm using com.saturnfive.comiczipper; if you prefer a different name, please let me know.

**Comment by pkrll** [comment]
Great. com.saturnfive.comiczipper is fine.

**Comment by mikemcduffie** [comment]
BTW the Apple Help Book system is case sensitive so it was com.SaturnFive to match your string(s). That bit me in the butt. :)

Do you want me to rework the credits section and/or add an anchor that you can use for the hyperlink in the about box? I have credits and acknowledgements all at one level.

**Comment by pkrll** [comment]
The credit section is fine. But do add an anchor there. I'm closing this issue now.

**Comment by mikemcduffie** [comment]
So add an Acknowledgements heading with anchor on the credits page?

**Comment by pkrll** [comment]
Yes, or just to the credit page without needing to create an acknow heading. Whatever is simplest/looks best

**Comment by mikemcduffie** [comment]
Credits are in the about box so I'm thinking an acknowledgements section on the credits page. Alternately, I could remove the credits and change the whole page to acknowledgements. Your call.

**Comment by pkrll** [comment]
No, no need to overdo it. Just add an anchor to the credits page.
