### ISSUE TITLE
Recommendation: Add a Changelog to the project

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#66]
Adding a Changelog (preferably in markup format) would provide a centralized place to look at all releases/updates and could be added to the help book.

**Comment by pkrll** [comment]
You mean as a section in the help book? I can see that.

**Comment by mikemcduffie** [comment]
Yes for the version history.

So far I have:

* ReadMe
    * Version history
    * System requirements
   * Installing, updating, uninstalling
   * License agreement
   * Credits
* Usage
* Settings
   * General
   * Exclude List
   * Advanced

Glossary

**Comment by mikemcduffie** [comment]
I suspect there is no need for official versioning info in the help book until a 1.0 style release. Any idea what version you're going to call it? I'm sure the 2.x means something to you, but I came in late so it's all seems pre-1.0 to me. ;) 

That said, it's  damn good app and very usable as is now.

**Comment by pkrll** [comment]
Yeah, 1.0 was a super bad app. I changed it to 2.0 when I rewrote it with a better design. But to go to 3 is too much of a leap, even if the app has had somewhat of a new design and changed a lot of the code. But I see 2.5.X as the release version. In the past I did go by semantic versioning, but it's started to make less and less sense to me, so instead I now go more by build version for bug fixes and small to medium size updates.

With the cancel buttons I'm thinking it warrants incrementing to 2.5.4.

**Comment by mikemcduffie** [comment]
I assume this includes the cell cancel/clear buttons as well?

**Comment by pkrll** [comment]
Yes (if Apple allows one to cancel an operation already in the queue, haven't had the chance to research that).

**Comment by mikemcduffie** [comment]
The Unarchiver does this. Perhaps look at that code?
