### ISSUE TITLE
Empty folders are excluded regardless of Exclude List settings

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#67]
I think this fine as I can think of no use for empty folders, but the Exclude List setting should be changed to "Exclude empty files" if the hardcoded behavior is not changed.

**Comment by pkrll** [comment]
It seems to be ZipUtilities that exclude those. I'll look into it.

**Comment by mikemcduffie** [comment]
Again, I don't think it's necessarily bad. We could remove the reference in the Exclude List option and explain it in the help book. I'm hard pressed to think a reason to leave empty folders. And if you did, it would be better to distinguish between initially empty and those empty after removing other excluded files.

Speaking of the help book, I'm about 40% through now. I'm probably being way too detailed on comic archive background. ;)

**Comment by pkrll** [comment]
Haha, sounds good.

Yeah, maybe I'll just change the label. It is easier, and does not create the risk of more bugs...

**Comment by mikemcduffie** [comment]
Actually the various metadata explanations took the most writeup so far. But they're all way back in Glossary so who knows how many will read it. ;) I will reference it in settings for those desiring additional information beyond what does this checkbox do.
