### ISSUE TITLE
2.5.3 (0769) Cancel item button erratic behavior

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#68]
Pressing an item's cancel/close button should remove the item from the list  and decrement the icon notification badge (see The Unarchiver's behavior). Leaving the item in the table view with a warning status badge indicates something went wrong in the compression (out of disk space, etc.) and confuses the user. One test produced a circle arrow status badge (retry?), but it did not function. 

I suspect the difference is canceling while compression is in-progress vs. canceling while queued for later processing. Either state should have the same result: item is removed from list and the icon notification badge count is decremented.

Not removing the item and decrementing the icon notification badge currently produces incorrect number of pending items in the icon notification badge and exhibits erratic behavior. In some tests, a negative number was displayed; in others a positive number that indicated the canceled item was still queued but there was way to resume. Subsequent item drops might produce higher or lower negative numbers even without further cancels. 

It seems cleaner and less prone to bugs to simply remove the item and decrement the icon notification badge count.

**Comment by mikemcduffie** [comment]
Clicking the Clear List button crashed the app with:

``` libc++abi.dylib: terminating with uncaught exception of type NSException ```

Not sure if you intended the button to be used to "Cancel All" but the label should be changed to reflect the intent if it's left active during item processing.

**Comment by pkrll** [comment]
Oh for Mike's sake, read your e-mail and recognise when a function is not ready. Not sure though if it is less prone to bugs to simply remove, the rows are indexed, if a item disappears the index is reset, and then the item currently in progress may not find it's row (item at row 5 goes to row 4, for example). Maybe there's some way.

The clear list button should be a cancel all, but I haven't gotten the cancel all operations method of NSOperationQueue to work properly.

**Comment by mikemcduffie** [comment]
Sorry not enough coffee yet. How do you want to handle reporting issues with the function?

**Comment by pkrll** [comment]
We can do it here now, it's fine.

**Comment by pkrll** [comment]
Can't remove them from the list without substantial changes, which is not worth it at this point. Did though fix some bugs, changed the appearance and added a cancel all button.

**Comment by mikemcduffie** [comment]
Looks like cancelling an in progress item isn't allowed. Suggest changing the badge during processing. I'll see what I can come up with.

**Comment by mikemcduffie** [comment]
How about a spinner?

**Comment by mikemcduffie** [comment]
If you don't want a spinner, I could make a version of this that matches the other badges:

![in_progress](https://cloud.githubusercontent.com/assets/4350221/10497780/aab13b06-727c-11e5-9363-44cacdc8644f.jpg)

**Comment by pkrll** [comment]
I have no problem cancelling in progress items.

**Comment by mikemcduffie** [comment]
It's a timing issue when I try. I'm using 2.5.4 (078A). If I press the cancel button before ~50% complete. It cancels. If I press after the midway point it completes.

I'm still seeing persistent icon notification buttons with negative numbers after all tasks are complete.

**Comment by pkrll** [comment]
Okay, I suspect it's the NSOperation that refuses. It's the NSOperation that decides to cancel or not.

**Comment by pkrll** [comment]
I can't reproduce your bugs. I can cancel whenever, and the count is correct.

**Comment by pkrll** [comment]
The only bug I can found is when an item that is in queue is aborted, the status and count does not change until it is that items turn to compress. I know the problem here, just trying to figure out a good solution.

**Comment by mikemcduffie** [comment]
Sent a separate email with my test procedure before I saw the second comment.
