### ISSUE TITLE
Table View should autoscroll

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#69]
When the number of cells exceeds the window size, the table view should autoscroll to show the current processing item.

**Edit by pkrll: Not a bug, so switched don't to should.**

**Comment by pkrll** [comment]
It'll be included in 2.6.0, which is not that far away.

**Comment by mikemcduffie** [comment]
Cool.Using the app more organically now as I cleanup some older scans. It works really well.

**Comment by pkrll** [comment]
Glad to hear it!
