### ISSUE TITLE
Ver 2.3.3: Wildcards in excluded file preference --> infinite progress spinner

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#7]
Really nice improvements in such a short time. :)

However there are no restrictions listed in the excluded file pref. Changing ".DS_Store" to ".*" (to exclude all unix style hidden files) produced an infinite spinner. App is not locked up. Pref drawer still works. As does Quit. No files produced in the target folder.

**Comment by mikemcduffie** [comment]
Looking at your default exclude string, it appears you may be assuming wildcards, .e.g. ".svn" for "*.svn". That maybe why ".*" caused a stalled compress (excludes every file or every file with extension?). (I keep wanted to say locked-up, but the app is obviously not locked up; just a background task.)

**Comment by mikemcduffie** [comment]
"._*" worked to exclude files starting with that string.

**Comment by pkrll** [comment]
It's the "zip" command line tool that is running in the background that gets locked-up, I think. I need to research how it works more in detail, but I think, after a quick glance, that using the --exclude flag the way I'm doing just excludes all files with that particular character(s) in it's name. So, excluding ".svn" should also exclude a file named "file.svn.jpg" for example. But it shouldn't be a problem finding a workaround here.

**Comment by pkrll** [comment]
I've kind of solved this issue in version 2.3.4. But exclusion still needs improvement, will add a new issue for it.
