### ISSUE TITLE
Folder names ending in a number have "#" inserted before the number

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#70]
Take  `Captain Video 001 (1951) (c2c)` and rename `Captain Video 001`. The resulting archive is named `Captain Video #001.cbz`.

**Comment by mikemcduffie** [comment]
You labeled this an enhancement. Just to be clear, I'm not asking for this function; I'm seeing it. 

I assume it's unintended.

**Comment by pkrll** [comment]
You assume wrong! :) I though it was a cool feature... Guess not. I'll remove it in 2.6.0.

**Comment by mikemcduffie** [comment]
Oh. No need to remove it, but I would recommend adding a setting in Advanced. Perhaps default off. 

"Different strokes for different folks" kind of a thing. Some like the hash, some don't. It was strange that it only worked when the issue number was the last item. It took me a little bit to figure out the trigger as I hadn't expected it to happen, hadn't seen it before and wasn't expecting it.

**Comment by pkrll** [comment]
Yes, the function is really not that smart, just adds the hash to the digits at the end of the name (if there are any). A setting makes sense.

Another setting I'm thinking about is Quit after compression. Would that be useful?

**Comment by mikemcduffie** [comment]
OH YES! I was thinking about that yesterday. I tend to use the archiver differently than I imaging you do. I just wanted a droplet that processed the files like The Unarchiver/XLD/Etc. 

The stuff you're doing is cool and I see the utility in being able to review what happened. So different behaviors for dropping on inactive app icon vs. dropping on launched app appealed to me.

I considered trying a branch that added droplet mode settings. Remove cell on task completion to keep focus on processing cell and quit on completion.

**Comment by mikemcduffie** [comment]
Something like `Enable Droplet mode" in advanced.

**Comment by pkrll** [comment]
Sounds cool! But do wait for 2.6.0 before branching. I'm (yet again...) rewriting the code, this time separating the code even more, making it more logical. Never thought anybody would be interested in this app, so I never really added much effort in that.

**Comment by mikemcduffie** [comment]
It's all a learning exercise for me. That and getting a cool utility.

I wasn't tracking the 2.6 branch until you mentioned it earlier. I'm interested to see where it goes.
