### ISSUE TITLE
2.6.0: Drag Target Window develops artifacts during use and reset

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#75]
During screen recording of the current version I discovered the Drag Target window is not reseting to its original state.

Initial State (2.6.0):

![screen shot 2015-10-25 at 9 28 21 am](https://cloud.githubusercontent.com/assets/4350221/10716599/59aa5d3c-7afb-11e5-83d7-3b92c57bda36.png)

After one operation and clear all from toolbar button, the text is now black (or at least darker thicker):

![screen shot 2015-10-25 at 9 28 40 am](https://cloud.githubusercontent.com/assets/4350221/10716604/73e5f594-7afb-11e5-8f4a-2b7adbac1dfd.png)

After a droplet mode rejection shake, I noticed the background image resizing was off and blocky and starts to exhibit aliasing on the text:

![screen shot 2015-10-25 at 9 42 55 am](https://cloud.githubusercontent.com/assets/4350221/10716640/f0b4eca0-7afc-11e5-9ac1-4c921acba5c5.png)

Additional shake rejections from droplet mode continued to deteriorate the image and text:

![screen shot 2015-10-25 at 9 45 40 am](https://cloud.githubusercontent.com/assets/4350221/10716663/49520c26-7afd-11e5-9a23-7005772ecdb1.png)

I also noticed at one point the window had shifted position. I think this may have happened after a rejection shake but I need to retest and see if I can recreate. I'm pretty sure I didn't drag the window as I was careful with placement for partial screen recording placement.

Quitting and restarting the app reset the original window format.

- All operations were done with the default/smallest window size. 
- Some operations had longer lists that involve Table View scrolling. 
- All Table View cell deletions were handled through the clear all toolbar button; no individual clears or cancels. 
- All processes were run to completion without errors.

**Comment by pkrll** [comment]
I suspect the problem lies in when the app reinstates the initial view. It probably creates new instances and puts them over the old one. This should happen every time the tableview is removed (regardless of operation state). And it should be an easy fix.

**Comment by pkrll** [comment]
Should be fixed in build 0995. (Also, I incremented version number to 2.6.1 as I forgot to do it before with the addition of the help book.)
