### ISSUE TITLE
No feedback for renamed archives to ensure unique filename

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#8]
There is no feedback to notify the use that a unique filename was created. More so the algorithm only checks the original folder name + cbz and creates a "-1" variation, but does not check it that is unique and overwrites any existing file.

Suggest adding a loop through numerically increases filename suffixes (-2, -3, ...).

Perhaps use the complete final filename (with extension) in the table view after compression is completed? The current view is nice as the custom icon shows up if you have a QLgenerator (I'm currently using Yet Comic Reader which has a nice preview icon) but the full filename resulting item would be a clue that file rename was needed. A alert would be obtrusive to me. 

The "Show in Finder" contact menu action is a nice touch. I'm really impressed with your progress.

**Comment by pkrll** [comment]
Thanks. I've been meaning to do something about the names, just been a little too lazy. But I'll look into it.

**Comment by pkrll** [comment]
Fixed in 2.4.0.
