### ISSUE TITLE
Ver. 2.3.3: Drag and drop previously processed folder has no obvious feedback

### ISSUE THREAD

**Issue by mikemcduffie** [pkrll/ComicZipper-2#9]
When you drop a previously processed folder on the window or app icon/alias (that you for the droplet support), there is no user feedback. It's left up to the user to figure out it is a duplicate. 

While the intended behavior is understandable, it is not obvious what is happening. Admittedly this is less likely if the delete folders pref is on, but if a user wants to reprocess a folder or mistakenly selects the wrong folder it isn't obvious what is happening.

Interestingly if you delete the resulting archive, you still can't reprocess the folder.

Suggest an alert or similar feedback mechanism. It may also help to add a Clear (list) button.

**Comment by pkrll** [comment]
Do you have any suggestions on how the user should be alerted? I'm not too keen on alert windows, or even an "error" notification.

A clear button is a great idea, I'll add a separate ticket for it.

I'm not sure I understand your second point, though. The user should not be able to add a folder to the list, while that same folder already is in the list. If the folder is removed, either before or after processing, then the user should be able to add it (again). This is how it works at least for me. The app is only concerned about and checks for duplicates in the table view list.

**Comment by mikemcduffie** [comment]
Agree on the alert dialog, but this may be a case where it's a necessary "evil" if the app behavior isn't changed. 

Other options are a temporary overlay (bezel window) or a notification center alert if 10.8 or higher. At the least there should be an alert sound.

Alternately you could remove the older item and re-add the folder which would not need an additional notification.

As far as the second point, I re-process folders for testing the app. The first time, it happened I didn't even realize I dragged the same folder as I have more than one with similar names. Alternately, the user could find an error with the resulting archive (need to edit image files, rename files for viewing order, change nested folders structure, etc.). A pre-flight test on the raw folder will resolve some of these, but it happens for me at least.

**Comment by pkrll** [comment]
Actually, there is already sort of a feedback system when dragging folders that already populate the list. 

The mouse badge icon only shows the number of valid items that can be added, which was originally my solution to the problem. The problem with an alert system or even an overlay is that when multiple files are dragged, it's hard to show that maybe just one was not added in a way that doesn't confuse the user even more.

![screen shot 2015-09-26 at 22 38 33](https://cloud.githubusercontent.com/assets/140205/10119753/e8d7bc7e-649f-11e5-8ee9-c5c69df0d54b.png)

But I'll look into making it possible to re-add folders that already been compressed in the list.

**Comment by mikemcduffie** [comment]
I hadn't noticed that as it's such a small detail. :)

As you say there's no obvious great way to handle this, I'd vote for simply repopulating the folder in the item list and correctly handling the dupe generated file issue.

**Comment by pkrll** [comment]
Processed folders can as of version 2.3.4 be added to the list again. But it should not be possible to re-add folders that have not been processed to the list. As for how to handle the feedback here, that feature really requires a redesign of the app, for it not to be obtrusive. I'm closing this ticket (as I interpret your issue more having to do with processed folders).
